### ISSUE TITLE
Need to be able to toggle cutting trees you don't own.

### ISSUE THREAD

**Issue by Smurfenstein** [loki79uk/FS22_LumberJack#10]
On some maps its a bit hard to see exactly what you own. Would be nice to have the ability to toggle if you want to be able to cut trees you dont own.

**Comment by loki79uk** [comment]
Not added this feature yet, but plan to add a configuration for this and anything else I can think of now that I have added user settings: https://github.com/loki79uk/FS22_LumberJack/releases/tag/v1.4.1.0

**Comment by loki79uk** [comment]
This can now be done in MP using the "LumberJack Chainsaw" permission on the Farm Management settings page.  I'm not sure about having a SP configuration for this, but it could potentially be a new setting in the menu for single player only - as long as it doesn't conflict with the MP setting.  https://github.com/loki79uk/FS22_LumberJack/releases/tag/v1.4.2.1

**Comment by loki79uk** [comment]
Adding this feature now, should be in the next release:
![image](https://user-images.githubusercontent.com/76516343/235370180-0d6a05c4-cfbf-491d-ae03-ad9444ae6b5a.png)
![image](https://user-images.githubusercontent.com/76516343/235370150-d401a74c-0bbf-42c8-a72d-5737b47c3336.png)

**Comment by loki79uk** [comment]
Please try the latest release now: https://github.com/loki79uk/FS22_LumberJack/releases/latest
