### ISSUE TITLE
Multiplayer/Dedicated Server Permissions

### ISSUE THREAD

**Issue by Xechorizo** [loki79uk/FS22_LumberJack#12]
Would love admin permissions (and maybe UI) to be able to disable super strength, adjust its value, or have a version of the mod without it. The QoL features are great, but not all features are desirable for all difficulties of playthrough.

Great mod!

**Comment by loki79uk** [comment]
Good timing with your request, I am literally working on that now.  Watch this space!
![image](https://user-images.githubusercontent.com/76516343/233805467-ccb353d9-ecc0-41d9-9056-255d6c6e848d.png)

**Comment by loki79uk** [comment]
I don't have a server wide settings menu yet, and can never have one for dedi, but I have made a start here: https://github.com/loki79uk/FS22_LumberJack/releases/tag/v1.4.1.0

**Comment by loki79uk** [comment]
Making some good progress at hijacking the game server permissions system:
![image](https://user-images.githubusercontent.com/76516343/234128660-72573691-7ac2-437b-958a-c882517f0d4b.png)

**Comment by loki79uk** [comment]
The MP permission system is working now in:  https://github.com/loki79uk/FS22_LumberJack/releases/tag/v1.4.2.1
