### ISSUE TITLE
Super Strength Toggle Error from 1 Client

### ISSUE THREAD

**Issue by Jayshua83** [loki79uk/FS22_LumberJack#15]
We are 2 Clients on a Dedi Server.

In the past couple days my client has started throwing this error when hitting ALT for Super Strength.

Error: Running LUA method 'update'.
dataS/scripts/player/Player.lua(3101) : attempt to perform arithmetic on local 'inputValue' (a nil value)

Not sure why it just started happening and only to me and not my wife...

Any ideas? Ver 1.4.0.0 will be updating later if that would matter!

**Comment by Jayshua83** [comment]
Also this LUA error is coming from the Dedi Server when 1 Client does the ALT. Clients show no errors....

**Comment by Jayshua83** [comment]
Annoying FS... Tried doing more testing and I can't get it to happen again... 

Happened several times and I had to quit the game each time to stop the server from lagging out... but Now I can't get it to happen! lol

I'll keep testing... Maybe it was happening in a very specific circumstance.

**Comment by Jayshua83** [comment]
I don't know what is going on but this might not even be related to Lumberjack!

Just had a huge AutoLoad issue too...

Going to continue banging head on wall! lol

**Comment by ddewar** [comment]
Just to help you feel less crazy, I also have run into this with Lumberjack (I think). Also, still trying to make it happen intentionally for debugging. 😆

**Comment by Jayshua83** [comment]
Have had this happen multiple times now on 2 different clients.

Any time it has happened it seems it is when Super Strength (ALT) is being used.

I feel like it is happening while the game Autosaves and you are carrying something? Still trying to troubleshoot!

**Comment by Jayshua83** [comment]
This just started in the past week or two as well!

So either another mod got updated somewhere is causing it or patch 1.9.1 is making it worse?

I have noticed a MAJOR change in Saving since 1.9.1 and I am not the only one, where the saves seem to take a lot longer (at least on DEDIS, don't play in SP enough to know)

No clue if any of this is part of the issue?

**Comment by loki79uk** [comment]
According to the game source then line 3101 is the jumping function:
![image](https://github.com/loki79uk/FS22_LumberJack/assets/76516343/9e29604b-aa31-48ab-9824-de0b46d2b3b7)

BUT the error is saying that the inputValue is `null`. I currently have no idea... :(

**Comment by loki79uk** [comment]
Closing for now, but please re-open if anything related to this happens again.

**Comment by Jayshua83** [comment]
This is still happening! GAHH... Can't figure this one out!

**Comment by Jayshua83** [comment]
Not sure how to reopen this... Maybe I need to make a new issue in reference?
