### ISSUE TITLE
Chainsaw RING adjustments

### ISSUE THREAD

**Issue by westor7** [loki79uk/FS22_LumberJack#17]
Hello,

Is it possible to make the RING a bit more visible (maybe an option under settings?), its too transparent right now and is almost hidden in few cases so i can hardly see it, and maybe an option to change the color? (except from GREEN RED BLUE and etc.. that these are used for an other functionality).

Example Images: 

![](https://i.imgur.com/IK6MHHj.jpeg)

![](https://i.imgur.com/OvOSST5.jpeg)

- Thanks!

**Comment by loki79uk** [comment]
Hi,  Yes you can certainly change it to any colour manually.  Try different values (R,G,B) for the "grey" ring selector around line 384:
```lua
	if LumberJack.stumpGrindingFlag and g_currentMission:getHasPlayerPermission("cutTrees") then
	-- SHOW RED RING SELECTOR
		setShaderParameter(hTool.ringSelector, "colorScale", 0.8, 0.05, 0.05, 1.0, false)
	else
	-- SHOW GREY RING SELECTOR
		setShaderParameter(hTool.ringSelector, "colorScale", 0.05, 0.05, 0.05, 1.0, false)
	end
```

I will think about a menu option to change all of the colours, and add a colour blind option too, but maybe just making it a bit brighter will be enough.

**Comment by westor7** [comment]
Oh nice! It's seems perfect..

`rgb(75,0,130)`

```lua
setShaderParameter(hTool.ringSelector, "colorScale", 75, 0, 130, 5.0, false)
```

![](https://i.imgur.com/MVflEb5.jpeg)

**Comment by loki79uk** [comment]
> Oh nice! It's seems perfect..

lol, I guess you can't miss it now.   It looks like a lightsabre!

**Comment by westor7** [comment]
> > Oh nice! It's seems perfect..
> 
> lol, I guess you can't miss it now. It looks like a lightsabre!

HAHA yeah :P
