### ISSUE TITLE
Cutting a tree issue

### ISSUE THREAD

**Issue by westor7** [loki79uk/FS22_LumberJack#26]
Hello,

When i try to cut a tree it doesn't allow me to cut it from the root so i lose some part of the tree because it's only allowing to cut it from the middle.

When i try to cut it from the root (not too bottom) it doesn't allow me:
![FarmingSimulator2022Game_2023-09-18_12-53-03](https://github.com/loki79uk/FS22_LumberJack/assets/3636159/bed5283e-730e-41b0-b33c-31571cf9a5db)

Here is the position that allows me to cut it:
![FarmingSimulator2022Game_2023-09-18_12-53-19](https://github.com/loki79uk/FS22_LumberJack/assets/3636159/7596d3f3-ed82-48e1-93a2-d96b2db177ba)

Settings (Using latest modhub version): 
![FarmingSimulator2022Game_2023-09-18_12-55-30](https://github.com/loki79uk/FS22_LumberJack/assets/3636159/6aaecd0e-2958-4b08-b10b-8f7ebf228623)

- Thanks!

**Comment by loki79uk** [comment]
Hi - this happens for me too (on Elmcreek), sorry about that!  I can't explain it apart from it seems to not happen on Silverrun where I did all of my testing!

![image](https://github.com/loki79uk/FS22_LumberJack/assets/76516343/2b863c26-54ec-4324-b25f-ef21c30eab2f)

**Comment by loki79uk** [comment]
I think I have found the issue - I'm pretty sure this is just how the chainsaw works in base game.  I.e. if you load the game without lumberjack, then the lowest point that you can cut will be the same.

I tried to override the cutting height, but then the tree doesn't fall down!!

See below - I made multiple cuts working up from the lowest one until it fell:
![image](https://github.com/loki79uk/FS22_LumberJack/assets/76516343/ad5fd446-eca2-4be1-88b1-835dec558363)

I'll keep looking into it, but for now could you please try without LumberJack to confirm that the cut height is the same as in your screen shots.

**Comment by westor7** [comment]
> I think I have found the issue - I'm pretty sure this is just how the chainsaw works in base game. I.e. if you load the game without lumberjack, then the lowest point that you can cut will be the same.
> 
> I tried to override the cutting height, but then the tree doesn't fall down!!
> 
> See below - I made multiple cuts working up from the lowest one until it fell: ![image](https://user-images.githubusercontent.com/76516343/268753869-ad5fd446-eca2-4be1-88b1-835dec558363.png)
> 
> I'll keep looking into it, but for now could you please try without LumberJack to confirm that the cut height is the same as in your screen shots.

Thanks for the detailed answer, now makes sense.
