### ISSUE TITLE
Super strength not working

### ISSUE THREAD

**Issue by thewhitewolfgamer** [loki79uk/FS22_LumberJack#27]
Idk why but it just stopped working. I tried reinstalling and removing all other mods I recently installed and still don't work

**Comment by loki79uk** [comment]
There is a setting for the amount of strength you get - have you changed that to something low?

**Comment by thewhitewolfgamer** [comment]
I double checked that because I know I lower it but it wasn't low it was set to infinite

**Comment by loki79uk** [comment]
Can you send me a log file?  I'm just going to sleep now as 1am, but will look tomorrow.

**Comment by thewhitewolfgamer** [comment]
[log.txt](https://github.com/loki79uk/FS22_LumberJack/files/14467416/log.txt)

**Comment by loki79uk** [comment]
I can't see anything obvious.  Try resetting your keybindings file (but back up the existing one first).

**Comment by thewhitewolfgamer** [comment]
I did get it to work but not fully. 
When I first start the map it doesn't work. But if I save the map I just started then leave then go back in it works just fine.
I'll get back with you on the resetting the key bindings if it resolves it fully 
edit: the resetting the keybindings didn't fix it

**Comment by loki79uk** [comment]
Okay, I think this is actually a known bug, but I had completely forgotten about it!! (sorry)

This is the removed workaround that used to solve the issue, but it was ugly and I still don't know the full implications (e.g. could break some other key bindings) so I have not added it back in: https://github.com/loki79uk/FS22_LumberJack/commit/8bb2f1d11b6765a3fe7621ef09e5930fdc7e24e6

**Comment by thewhitewolfgamer** [comment]
ok
edit: adding those line's of code back in fixed it
