### ISSUE TITLE
Fix for patch 1.4/1.4.1

### ISSUE THREAD

**Issue by dexus92** [loki79uk/FS22_LumberJack#3]
Please fix your great mod for patch 1.4/1.4.1
Thanks!

**Comment by loki79uk** [comment]
What is not working for you?  It is okay for me on SP and MP.  Could it be the keybinding issue?  Try resetting your key bindings and see if that helps.

**Comment by dexus92** [comment]
Yes, You have right, it was missing keybinds after patch ;)
