### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by loki79uk** [loki79uk/FS22_LumberJack#32]
@vitalii2011 Can you please check the latest state, and also let me know if this is correct:
```xml
<text name="setting_lumberJack_showDebug" text="Показать отладочный дисплей"/>
<text name="toolTip_lumberJack_showDebug" text="Печать текста отладки и наложения для области обнаружения."/>
```

**Comment by vitalii2011** [comment]
I think that translation for these lines is not needed - users who know what "Debugging Display" is also know English. ;)
For "setting_lumberJack_showDebug" the translation is normal, and I will not undertake to translate the next line, but now its translation is a set of Russian words with an elusive meaning. )

**Comment by loki79uk** [comment]
The debugging display is mainly visual - showing the outlines of foliage to destroy

**Comment by vitalii2011** [comment]
Then like this: 
`<text name="toolTip_lumberJack_showDebug" text="Показать текстовую и визуальную информацию мода для отладки."`

**Comment by loki79uk** [comment]
Thank you!  I have included this in the latest submission to GIANTS.
