### ISSUE TITLE
FS22 Lumberjack nopt working in multiplayer/dedicated server

### ISSUE THREAD

**Issue by billieidle** [loki79uk/FS22_LumberJack#5]
I noticed that deleting trees by using the chainsaw red ring no longer works in multiplayer. When the tree or stump is supposed to disappear the chainsaw snaps back a bit but just continues to saw and spew sahavings. Nothing else happens. In career mode it still works like a charm :)

Do we know why this is?

**Comment by loki79uk** [comment]
That must be due to the recent update to fix the un-deleted trees bug #4.  I thought I tested that in MP, but I guess not!  You can always go back to the previous release for now while I look into it: https://github.com/loki79uk/FS22_LumberJack/releases/tag/v1.1.0.0-beta

**Comment by billieidle** [comment]
Omg, that was quick. Thanks! :D

**Comment by billieidle** [comment]
Not sure how to download mods manually. Any chance you can point me in the right direction? Removing the mod from the server and uploading the previous release to the server and placing it in the mod folder on the harddrive seems like the logical way to go.

**Comment by loki79uk** [comment]
I think it was the most embarrasing mistake I've ever made!
![image](https://user-images.githubusercontent.com/76516343/175495588-a44ad3a8-7240-4601-be5d-1c193370c0ea.png)

At least easy to fix. New release incoming.

**Comment by loki79uk** [comment]
Please try this release:  https://github.com/loki79uk/FS22_LumberJack/releases/tag/v1.2.1.0
