### ISSUE TITLE
Super strength doesn't work anymore with patch 1.8.1.0

### ISSUE THREAD

**Issue by aurelien2023** [loki79uk/FS22_LumberJack#6]
Super strength doesn't work anymore with patch 1.8.1.0
same in [FS22_easyDevelopmentControls]

**Comment by loki79uk** [comment]
Should be fixed now in the latest release:
https://github.com/loki79uk/FS22_LumberJack/releases/tag/v1.3.1.0

**Comment by aurelien2023** [comment]
Works fine for me too
